services:
  - type: web
    name: sudoku-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --timeout 120"
    autoDeploy: true
